### ISSUE TITLE
Cannot create property display 

### ISSUE THREAD

**Issue by SteveEdson** [gridsome/gridsome#235]
just updated to 0.5.4 from 0.5.0, only changed the version, nothing else but suddenly getting the error message during build:

```
Cannot create property 'display' on string ' background-image: url(/images/my-image.png);'
```

Not sure if I need to change something, but thought it was worth flagging as it wasn't an issue before.

**Comment by hjvedvik** [comment]
What does the template or component where you have `background-image: url(/images/wifi.png);` look like?

**Comment by SteveEdson** [comment]
It's not the cleanest right now due to my old Jekyll content, but it's done via a filter:

```html
<div :class="['post-grid__item', project.node.image ? 'has-image' : 'no-image' ]" v-for="project in $static.allProject.edges" :key="project.node.id" :style="project.node | generateBackground">
```

```js
Vue.filter('generateBackground', (node) => {
        let styles = '';

        if(node.image)  styles += ` background-image: url(${node.image});`;
        if(node.imageStyle) styles += ` ${node.imageStyle}`;
        if(!node.image && node.background) styles += ` background: ${node.background}`;

        return styles;
    });
```

**Comment by hjvedvik** [comment]
Did you use the same version of Vue before and after you updated Gridsome? I'm able to get the same error message with this code `<span v-show="false" :style="node | generateBackground"></span>` when the filter returns a string. But it works when the filter returns an object instead.

**Comment by hjvedvik** [comment]
I created a test in the Vue repo and got the same error. So it's a bug with `vue-server-renderer`.

**Comment by robaxelsen** [comment]
@hjvedvik Is this something that we should report upstream, keeping this issue open until it's resolved in `vue-server-renderer`?

**Comment by JuanDelgado06** [comment]
I also have a similar problem, this is my problem:

Could not generate HTML for "/about/":
TypeError: Cannot create property 'display' on string 'bottom:50px;right:40px;'
    at Object.show (C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:17395)
    at C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:68087
    at C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:68353
    at eo (C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:68574)    
    at C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:70675
    at Yi (C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:67165)    
    at io (C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:70577)    
    at ro (C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:70208)    
    at eo (C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:67455)    
    at C:\Users\Juan Delgado\Documents\GitHub\codepici-blog\node_modules\vue-server-renderer\build.prod.js:1:70675

Does anyone know how I can fix it?

**Comment by felixiho** [comment]
Hi
This sometimes happens if the style is passed into an element that's not being displayed. 
Example is when you have something like:

`<div v-show='false' :style='styles'></div> `

A simple fix could be:
`<div v-show='showDiv' :style='showDiv ? styles : '' '></div> `

**Comment by SupremeSalvatore** [comment]
Are there any other known issues?
I have removed everything with that semanthics and still getting error:
`TypeError: Cannot create property 'display' on string 'bottom:40px;right:30px;'`

**Comment by felixiho** [comment]
@SupremeSalvatore Do you have any vue directives that might dynamically affect the elements rendering?
Perhaps you can share the element

**Comment by SupremeSalvatore** [comment]
First of all, im not even sure that is the element since this is dynamic page.
Try this since its a template which should be displayed for section:
```html
<template>
  <Layout>
    <content-header :title="$page.section.title" :sub="subTitle"></content-header>

    <div class="container mx-auto">
      <div class="flex flex-wrap my-4">
        <CardItem
          v-for="edge in $page.section.belongsTo.edges"
          :key="edge.node.id"
          :record="edge.node"
        />
      </div>

      <div class="pagination flex justify-center mb-8">
        <Pagination
          :baseUrl="$page.section.path"
          :currentPage="$page.section.belongsTo.pageInfo.currentPage"
          :totalPages="$page.section.belongsTo.pageInfo.totalPages"
          :maxVisibleButtons="5"
          v-if="$page.section.belongsTo.pageInfo.totalPages > 1"
        />
      </div>
    </div>
  </Layout>
</template>
```

**Comment by SupremeSalvatore** [comment]
I have resolved this successfully, the problem was with `vue-backtotop` component it couldn't be server-rendered, so I needed to wrap that component in `<ClientOnly>`.
Aswell I encounter an issue where I was using `localStorage` needed to wrap that in conditional to check `process.isClient` so it could be rendered. Hopefully, this helps someone starting out as well.
