### ISSUE TITLE
TypeError: Cannot read property 'typeName' of undefined

### ISSUE THREAD

**Issue by nolfranklin** [gridsome/gridsome#521]
## Description

Seeing non-descriptive error (below) on `gridsome build` and `gridsome develop`.

```
TypeError: Cannot read property 'typeName' of undefined
    at fieldValue (.../node_modules/gridsome/lib/graphql/createFieldDefinitions.js:43:23)
    at fieldValues (.../node_modules/gridsome/lib/graphql/createFieldDefinitions.js:26:16)
    at createFieldDefinitions (.../node_modules/gridsome/lib/graphql/createFieldDefinitions.js:9:14)
    at module.exports.store (.../node_modules/gridsome/lib/graphql/nodes/index.js:14:20)
    at module.exports.store (.../node_modules/gridsome/lib/graphql/createSchema.js:7:41)
    at App.createSchema (.../node_modules/gridsome/lib/app/App.js:168:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Expected result

Build is successful. 

### Environment

package.json:
```
{
  "name": "siteName",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/source-contentful": "^0.3.0",
    "gridsome": "^0.6.4",
    "vue-showdown": "^2.4.1"
  },
  "devDependencies": {
    "gridsome-plugin-purgecss": "^1.0.12",
    "gridsome-plugin-tailwindcss": "^1.3.2"
  }
}
```

gridsome.config.js
```
module.exports = {
	siteName: 'SiteName',
	plugins: [
		{
			use: 'gridsome-plugin-tailwindcss'
		},
		{
			use: 'gridsome-plugin-purgecss'
		},
		{
			use: '@gridsome/source-contentful',
			options: {
				space: process.env.xyz,
				accessToken: process.env.xyz,
				host: 'cdn.contentful.com',
				environment: 'master',
				typeName: 'Contentful',
				routes: {
					'Tag': '/tags/:slug',
					'Article': '/articles/:slug',
					'Page': ':slug'
				}
			}
		}
	]
}
```

For Tooling issues:
- Node version: v10.14.2
- Platform: Mac

### Notes:

- Ran npm install/update today and noticed @gridsome/source-contentful had been updated today but unsure if that's related.
- Tried upgrading/downgrading Gridsome and Contentful in package.json

**Comment by nolfranklin** [comment]
Fixed. Related to featured content being unpublished/deleted in Contentful.

**Comment by ukristen** [comment]
Hi Nol, how did you fix it? I am facing the same issue after deleting content in Contentful.

**Comment by jxlstudio** [comment]
@ukristen I encountered this issue and spent hours searching my code for bugs. I had unpublished a singe photo. I republished it, but replaced the photo in the Contentful record, as to keep the same record id. This fixed my issue.

**Comment by ukristen** [comment]
Thanks, @jxlstudio.

**Comment by joranquinten** [comment]
This didn't solve my issue, since the photo was completely deleted (non recoverable). It's not helpful that the build doesn't give a decent pointer. For those encountering this, I've change lines 75:81 in the gridsome/lib/graphql/createFieldDefinitions.js (v 0.7.16) into:

```
      for (let i = 0; i < length; i++) {
        if (value[i] && value[i].hasOwnProperty('typeName')){
          if (!value[i].typeName) {
            warn(`Missing typeName for reference at: ${path.join('.')}.${i}`)
          } else if (!currentValue.typeName.includes(value[i].typeName)) {
            currentValue.typeName.push(value[i].typeName)
          }
        } else {
          warn(`Missing typeName property for reference at: ${path.join('.')}.${i}`)
        }
      }
```

Which at least points into the right direction. This way I was able to find the deleted photos which were linked in other entries.

**Comment by maximilliangeorge** [comment]
> This didn't solve my issue, since the photo was completely deleted (non recoverable). It's not helpful that the build doesn't give a decent pointer. For those encountering this, I've change lines 75:81 in the gridsome/lib/graphql/createFieldDefinitions.js (v 0.7.16) into:
> 
> ```
>       for (let i = 0; i < length; i++) {
>         if (value[i] && value[i].hasOwnProperty('typeName')){
>           if (!value[i].typeName) {
>             warn(`Missing typeName for reference at: ${path.join('.')}.${i}`)
>           } else if (!currentValue.typeName.includes(value[i].typeName)) {
>             currentValue.typeName.push(value[i].typeName)
>           }
>         } else {
>           warn(`Missing typeName property for reference at: ${path.join('.')}.${i}`)
>         }
>       }
> ```
> 
> Which at least points into the right direction. This way I was able to find the deleted photos which were linked in other entries.

This was a huge help and a great improvement. You should submit this as a PR.
